name: Hello World
'on':
  workflow_dispatch: 
  #push
  #schedule:
  #  - cron: "*/1 * * * *"
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'
